function E = energy(S)
  sumOfNeighbors = ...
      circshift(S, [ 0  1]) ...
    + circshift(S, [ 0 -1]) ...
    + circshift(S, [ 1  0]) ...
    + circshift(S, [-1  0]);
Em = -S .* sumOfNeighbors;
E  = 0.5 * sum(Em(:));
end